import { BoardElement, BoardTemplate } from '../types/collabBoard';

export interface TemplateDefinition {
  id: BoardTemplate;
  name: string;
  description: string;
  badge: string;
  color: string;
  generateElements: (authorId: string, authorName: string) => Record<string, BoardElement>;
}

export const BOARD_TEMPLATES: Record<BoardTemplate, TemplateDefinition> = {
  blank: {
    id: 'blank',
    name: 'Kanvas Bebas',
    description: 'Kanvas kosong untuk eksplorasi bebas, coretan digital, dan curah gagasan santai.',
    badge: 'Eksplorasi',
    color: 'from-amber-400 to-orange-500',
    generateElements: (authorId, authorName) => {
      const now = new Date().toISOString();
      const elements: Record<string, BoardElement> = {
        welcome_note: {
          id: 'welcome_note',
          type: 'sticky',
          x: 400,
          y: 200,
          width: 220,
          height: 180,
          color: '#FEF08A', // pastel yellow
          text: '👋 Selamat Datang di Papan Ide!\n\nTempel ide hebatmu di sini menggunakan Sticky Note warna-warni!',
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
      };
      return elements;
    },
  },
  kwl: {
    id: 'kwl',
    name: 'Tabel KWL (Tahu - Ingin - Pelajari)',
    description: 'Model refleksi belajar: Apa yang sudah kutahu, apa yang ingin kutahu, dan apa yang kupelajari.',
    badge: 'Model KWL',
    color: 'from-blue-500 to-indigo-600',
    generateElements: (authorId, authorName) => {
      const now = new Date().toISOString();
      const elements: Record<string, BoardElement> = {
        header_k: {
          id: 'header_k',
          type: 'shape',
          shapeType: 'rectangle',
          x: 100,
          y: 100,
          width: 320,
          height: 60,
          color: '#DBEAFE', // blue-100
          text: '💡 K - Apa yang Sudah Kutahu?',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        header_w: {
          id: 'header_w',
          type: 'shape',
          shapeType: 'rectangle',
          x: 460,
          y: 100,
          width: 320,
          height: 60,
          color: '#FEF08A', // yellow-100
          text: '❓ W - Apa yang Ingin Kutahu?',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        header_l: {
          id: 'header_l',
          type: 'shape',
          shapeType: 'rectangle',
          x: 820,
          y: 100,
          width: 320,
          height: 60,
          color: '#DCFCE7', // green-100
          text: '🌟 L - Apa yang Kupelajari Hari Ini?',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        hint_k: {
          id: 'hint_k',
          type: 'sticky',
          x: 140,
          y: 190,
          width: 240,
          height: 160,
          color: '#BFDBFE',
          text: 'Tulis hal-hal yang sudah kamu ketahui sebelum materi dimulai.',
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        hint_w: {
          id: 'hint_w',
          type: 'sticky',
          x: 500,
          y: 190,
          width: 240,
          height: 160,
          color: '#FEF08A',
          text: 'Pertanyaan atau hal apa yang membuatmu penasaran?',
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        hint_l: {
          id: 'hint_l',
          type: 'sticky',
          x: 860,
          y: 190,
          width: 240,
          height: 160,
          color: '#BBF7D0',
          text: 'Kesimpulan atau wawasan baru setelah berdiskusi.',
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
      };
      return elements;
    },
  },
  frayer: {
    id: 'frayer',
    name: 'Diagram Frayer (Konsep Materi)',
    description: 'Analisis konsep mendalam melalui Definisi, Ciri-ciri, Contoh, dan Bukan Contoh.',
    badge: 'Analisis Konsep',
    color: 'from-emerald-500 to-teal-600',
    generateElements: (authorId, authorName) => {
      const now = new Date().toISOString();
      const elements: Record<string, BoardElement> = {
        center_circle: {
          id: 'center_circle',
          type: 'shape',
          shapeType: 'circle',
          x: 470,
          y: 270,
          width: 260,
          height: 260,
          color: '#FDE047',
          text: '🎯 TOPIK UTAMA\n(Tulis Istilah/Materi)',
          fontSize: 18,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        quad_1: {
          id: 'quad_1',
          type: 'shape',
          shapeType: 'rectangle',
          x: 100,
          y: 80,
          width: 320,
          height: 50,
          color: '#E0E7FF',
          text: '1. Definisi / Pengertian',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        quad_2: {
          id: 'quad_2',
          type: 'shape',
          shapeType: 'rectangle',
          x: 780,
          y: 80,
          width: 320,
          height: 50,
          color: '#FEF3C7',
          text: '2. Ciri-Ciri / Karakteristik',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        quad_3: {
          id: 'quad_3',
          type: 'shape',
          shapeType: 'rectangle',
          x: 100,
          y: 440,
          width: 320,
          height: 50,
          color: '#DCFCE7',
          text: '3. Contoh Nyata',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        quad_4: {
          id: 'quad_4',
          type: 'shape',
          shapeType: 'rectangle',
          x: 780,
          y: 440,
          width: 320,
          height: 50,
          color: '#FFE4E6',
          text: '4. Bukan Contoh',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
      };
      return elements;
    },
  },
  brainstorm: {
    id: 'brainstorm',
    name: 'Curah Gagasan 4 Kuadran',
    description: 'Memetakan ide bersama teman sekelas ke dalam 4 kelompok pemikiran terarah.',
    badge: 'Brainstorming',
    color: 'from-violet-500 to-purple-600',
    generateElements: (authorId, authorName) => {
      const now = new Date().toISOString();
      const elements: Record<string, BoardElement> = {
        title_box: {
          id: 'title_box',
          type: 'text',
          x: 350,
          y: 40,
          width: 500,
          height: 50,
          color: 'transparent',
          textColor: '#1E293B',
          text: '✨ Peta Curah Gagasan Kelas ✨',
          fontSize: 24,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        box_1: {
          id: 'box_1',
          type: 'shape',
          shapeType: 'rectangle',
          x: 120,
          y: 110,
          width: 440,
          height: 50,
          color: '#EDE9FE',
          text: '💡 Ide & Inspirasi Baru',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        box_2: {
          id: 'box_2',
          type: 'shape',
          shapeType: 'rectangle',
          x: 620,
          y: 110,
          width: 440,
          height: 50,
          color: '#FEF9C3',
          text: '⭐ Manfaat Bagi Kita',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        box_3: {
          id: 'box_3',
          type: 'shape',
          shapeType: 'rectangle',
          x: 120,
          y: 420,
          width: 440,
          height: 50,
          color: '#FFE4E6',
          text: '🛠️ Tantangan & Cara Mengatasi',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        box_4: {
          id: 'box_4',
          type: 'shape',
          shapeType: 'rectangle',
          x: 620,
          y: 420,
          width: 440,
          height: 50,
          color: '#DCFCE7',
          text: '🚀 Langkah Nyata yang Akan Dibuat',
          fontSize: 16,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
      };
      return elements;
    },
  },
  reflection: {
    id: 'reflection',
    name: 'Refleksi Perasaan & Pembelajaran',
    description: 'Ekspresi perasaan siswa selama pembelajaran, hal yang dipahami, dan apresiasi teman.',
    badge: 'Sosial Emosional',
    color: 'from-pink-500 to-rose-600',
    generateElements: (authorId, authorName) => {
      const now = new Date().toISOString();
      const elements: Record<string, BoardElement> = {
        col_1: {
          id: 'col_1',
          type: 'shape',
          shapeType: 'rectangle',
          x: 80,
          y: 90,
          width: 250,
          height: 55,
          color: '#FEF08A',
          text: '😊 Senang & Bangga',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        col_2: {
          id: 'col_2',
          type: 'shape',
          shapeType: 'rectangle',
          x: 360,
          y: 90,
          width: 250,
          height: 55,
          color: '#BFDBFE',
          text: '💡 Wawasan Baru',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        col_3: {
          id: 'col_3',
          type: 'shape',
          shapeType: 'rectangle',
          x: 640,
          y: 90,
          width: 250,
          height: 55,
          color: '#FBCFE8',
          text: '🤔 Masih Bingung',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
        col_4: {
          id: 'col_4',
          type: 'shape',
          shapeType: 'rectangle',
          x: 920,
          y: 90,
          width: 250,
          height: 55,
          color: '#BBF7D0',
          text: '👏 Apresiasi Teman',
          fontSize: 15,
          authorId,
          authorName,
          authorRole: 'teacher',
          createdAt: now,
          updatedAt: now,
        },
      };
      return elements;
    },
  },
};

export const STICKY_COLORS = [
  { id: 'yellow', bg: '#FEF08A', border: '#FACC15', text: '#713F12', name: 'Kuning Mentari' },
  { id: 'green', bg: '#BBF7D0', border: '#4ADE80', text: '#14532D', name: 'Hijau Daun' },
  { id: 'blue', bg: '#BAE6FD', border: '#38BDF8', text: '#0C4A6E', name: 'Biru Langit' },
  { id: 'pink', bg: '#FBCFE8', border: '#F472B6', text: '#831843', name: 'Merah Muda' },
  { id: 'orange', bg: '#FED7AA', border: '#FB923C', text: '#7C2D12', name: 'Jingga Cerah' },
  { id: 'purple', bg: '#DDD6FE', border: '#A78BFA', text: '#4C1D95', name: 'Ungu Lavender' },
];

export const PEN_COLORS = [
  { hex: '#1E293B', name: 'Hitam Pekat' },
  { hex: '#2563EB', name: 'Biru Cerah' },
  { hex: '#DC2626', name: 'Merah Semangat' },
  { hex: '#16A34A', name: 'Hijau Segar' },
  { hex: '#D97706', name: 'Kuning Jingga' },
  { hex: '#9333EA', name: 'Ungu Kreatif' },
];

export const STROKE_WIDTHS = [
  { width: 3, label: 'Halus' },
  { width: 6, label: 'Sedang' },
  { width: 12, label: 'Tebal' },
];
